name: Deploy Staging

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  run-tests:
    uses: timeliness-app/timeliness-backend/.github/workflows/tests.yaml@main
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_APP_ENV: staging
          envkey_BASE_URL: https://staging.api.timeliness.app
          envkey_FRONTEND_BASE_URL: https://staging.web.timeliness.app
          envkey_CORS: staging.web.timeliness.app
          envkey_GCP_PROJECT_ID: project-tasks-294214
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
          envkey_DATABASE: ${{ secrets.DATABASE_STAGING }}
          envkey_SECRET: ${{ secrets.SECRET_STAGING }}
          envkey_SCHEDULER_SECRET: ${{ secrets.SCHEDULER_SECRET }}
          envkey_GCP_AUTH_CREDENTIALS: ${{ secrets.GCP_AUTH_CREDENTIALS }}
          envkey_FIREBASE: ${{ secrets.FIREBASE }}
          envkey_REDIS: ${{ secrets.REDIS }}
          envkey_REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          envkey_SENDINBLUE: ${{ secrets.SENDINBLUE }}
          envkey_STRIPE: ${{ secrets.STRIPE }}
          envkey_STRIPE_TEST: ${{ secrets.STRIPE_TEST }}
          envkey_STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          envkey_STRIPE_WEBHOOK_SECRET_TEST: ${{ secrets.STRIPE_WEBHOOK_SECRET_TEST }}
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_BUILD_CREDENTIALS }}
      - id: deploy
        name: Deploy to App engine
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app-staging.yaml
      - id: test
        run: 'curl "${{ steps.deploy.outputs.url }}"'