name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    uses: timeliness-app/timeliness-backend/.github/workflows/tests.yaml@main
  deployment:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}