name: Deploy Staging

on:
  push:
    branches: [ staging ]

jobs:
  run-tests:
    uses: timeliness-app/timeliness-backend/.github/workflows/tests.yaml@main
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: deploy
        name: Deploy to App engine
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          deliverables: app-staging.yaml